
export class FeedArticleBean{

   apkLink: string;
   author: string;
   chapterId: number;
   chapterName: string;
   collect : boolean;
   courseId :number;
   desc: string;
   envelopePic: string;
   id: number;
   link: string;
   niceDate: string;
   origin: string;
   projectLink: string;
   superChapterId: number;
   superChapterName: string;
   publishTime: number;
   title: string;
   visible: number;
   zan: number;

}
